version: '3.4'

services:
  postgres_image:
    image: postgres:latest
    container_name: postgres_image
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      #- ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "orderinguser"
      POSTGRES_PASSWORD: "orderinguser"
      POSTGRES_DB: "orderingdb"
    networks:
        - hadi-container-network
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
        - hadi-container-network

  rabbitmqservice:
    restart: unless-stopped
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmqservice
    ports:
        - 5674:5672
        - 15674:15672
    environment:
        - RABBITMQ_DEFAULT_USER=rabbituser
        - RABBITMQ_DEFAULT_PASS=rabbitpwd
    #volumes:
    #    - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #    - ~/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    networks:
        - hadi-container-network

  infrastructure.api:
    image: ${DOCKER_REGISTRY-}infrastructureapi
    build:
      context: .
      dockerfile: src/services/InfrastructureSvc/Infrastructure.API/Dockerfile
    networks:
        - hadi-container-network
    depends_on:
        - "rabbitmqservice"
        

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/services/OrderSvc/Ordering.API/Dockerfile
    networks:
        - hadi-container-network
    depends_on:
        - "rabbitmqservice"
        - "mongodb"
        - "postgres_image"

networks:
  hadi-container-network:
   driver: bridge

volumes:
  rabbitmqservice:
    driver: local
    name: rabbitmqservice
    external:
        false
  db_volume: